"""db_creation3

Revision ID: 0444a658ae14
Revises: 7453b648c72c
Create Date: 2023-02-12 18:41:37.235627

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0444a658ae14'
down_revision = '7453b648c72c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('first_flight', sa.String(length=15), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rockets_id'), 'rockets', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rockets_id'), table_name='rockets')
    op.drop_table('rockets')
    # ### end Alembic commands ###
