"""db_creation

Revision ID: 49ffff3dbc74
Revises: 5c8436daab73
Create Date: 2023-02-12 16:56:46.548439

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '49ffff3dbc74'
down_revision = '5c8436daab73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
