"""db_creation2

Revision ID: 7453b648c72c
Revises: 49ffff3dbc74
Create Date: 2023-02-12 18:26:59.127334

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7453b648c72c'
down_revision = '49ffff3dbc74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
