"""first_db

Revision ID: 24f8f507bcaf
Revises: 397826f69ae6
Create Date: 2023-02-15 16:11:01.964228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f8f507bcaf'
down_revision = '397826f69ae6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
