"""first_db

Revision ID: 2e001a06b5fd
Revises: 4cb26eeb9842
Create Date: 2023-02-15 15:50:04.000695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e001a06b5fd'
down_revision = '4cb26eeb9842'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
