"""first_db

Revision ID: 397826f69ae6
Revises: 8bab342593c1
Create Date: 2023-02-15 16:10:16.664441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397826f69ae6'
down_revision = '8bab342593c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
