"""first_db

Revision ID: 39d6ecac4f54
Revises: 842bfcc74cff
Create Date: 2023-02-15 17:49:20.938319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d6ecac4f54'
down_revision = '842bfcc74cff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
