"""first_db

Revision ID: 41a7e40de093
Revises: ccc96cf0ed9e
Create Date: 2023-02-15 17:43:49.460566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a7e40de093'
down_revision = 'ccc96cf0ed9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
