"""first_db

Revision ID: 4cb26eeb9842
Revises: d00384f8adcb
Create Date: 2023-02-15 15:38:25.096412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb26eeb9842'
down_revision = 'd00384f8adcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
