"""first_db

Revision ID: 4f003d566af1
Revises: 39d6ecac4f54
Create Date: 2023-02-15 17:49:45.867558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f003d566af1'
down_revision = '39d6ecac4f54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
