"""first_db

Revision ID: 4f6f66be8009
Revises: 24f8f507bcaf
Create Date: 2023-02-15 17:19:43.844509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6f66be8009'
down_revision = '24f8f507bcaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
