"""first_db

Revision ID: 61f7369f1ed5
Revises: 4f003d566af1
Create Date: 2023-02-15 17:59:23.585763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f7369f1ed5'
down_revision = '4f003d566af1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
