"""first_db

Revision ID: 76c6f4502906
Revises: 41a7e40de093
Create Date: 2023-02-15 17:44:14.454062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c6f4502906'
down_revision = '41a7e40de093'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
