"""first_db

Revision ID: 7858b5abcf16
Revises: 2e001a06b5fd
Create Date: 2023-02-15 15:50:43.164688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7858b5abcf16'
down_revision = '2e001a06b5fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
