"""first_db

Revision ID: 842bfcc74cff
Revises: f554d0284a44
Create Date: 2023-02-15 17:48:44.710977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842bfcc74cff'
down_revision = 'f554d0284a44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
