"""first_db

Revision ID: 89ddded8ba32
Revises: aacb17e4847e
Create Date: 2023-02-15 17:21:43.816769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ddded8ba32'
down_revision = 'aacb17e4847e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
