"""first_db

Revision ID: 952b431d6fa5
Revises: a78ceaa1c5d5
Create Date: 2023-02-15 17:46:38.986247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952b431d6fa5'
down_revision = 'a78ceaa1c5d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
