"""first_db

Revision ID: 9d9a208b26aa
Revises: 4f6f66be8009
Create Date: 2023-02-15 17:20:31.704353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9a208b26aa'
down_revision = '4f6f66be8009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
