"""first_db

Revision ID: a78ceaa1c5d5
Revises: e342349da333
Create Date: 2023-02-15 17:46:11.435036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78ceaa1c5d5'
down_revision = 'e342349da333'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
