"""first_db

Revision ID: aacb17e4847e
Revises: 9d9a208b26aa
Create Date: 2023-02-15 17:21:18.695674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aacb17e4847e'
down_revision = '9d9a208b26aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
