"""db_creation

Revision ID: ccc96cf0ed9e
Revises: 95aff61b8b40
Create Date: 2023-02-15 17:43:02.076915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc96cf0ed9e'
down_revision = '95aff61b8b40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
