"""first_db

Revision ID: d127e32875d2
Revises: 7858b5abcf16
Create Date: 2023-02-15 15:59:06.662353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd127e32875d2'
down_revision = '7858b5abcf16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
