"""first_db

Revision ID: de4b2d6850c4
Revises: 76c6f4502906
Create Date: 2023-02-15 17:45:09.111685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de4b2d6850c4'
down_revision = '76c6f4502906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
