"""first_db

Revision ID: f554d0284a44
Revises: 952b431d6fa5
Create Date: 2023-02-15 17:47:29.281456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f554d0284a44'
down_revision = '952b431d6fa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
